import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ISpineItem, Spine } from "@/components";
import { LuHome, LuListTodo, LuStickyNote } from "react-icons/lu";
import StoreProvider from "./StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const spineItems: ISpineItem[] = [
  {
    name: "Notebooks",
    displayName: "Notebooks",
    link: "/notebooks",
    icon: <LuStickyNote size={18} />,
  },
  {
    name: "Todos",
    displayName: "Todos",
    link: "/todos",
    icon: <LuListTodo size={18} />,
  }
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`root-container ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="root-navigation">
          <Spine middleItems={spineItems}/>
        </div>
        <div className="root-content">
          <StoreProvider>
            {children}
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
